version: '3.8'

services:
  # Servicio de la aplicación Spring Boot
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/orderdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_EXCHANGE=order.exchange
      - RABBITMQ_ROUTING_KEY=order.key
      - RABBITMQ_QUEUE=order.queue
    networks:
      - order-network
      - microservices-network

  # Servicio de base de datos PostgreSQL
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=orderdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - order-network

networks:
  order-network:
    driver: bridge
  microservices-network:
    external: true

volumes:
  postgres_data: 